---
- hosts: all
  become: yes
  become_method: sudo

  tasks:
  - name: Ensure SCAP Security Guide dependencies are installed
    package:
      name:
      - git
      - make
      - cmake
      - openscap-utils
      - openscap-scanner
      - scap-workbench
      - wget  # needed for the NIST test suite for SSG
      - gedit
      state: installed

  - name: Ensure SCAP Security Guide dependencies are installed (RHEL7)
    package:
      name:
      - python-jinja2  # needed for the new SSG yaml/jinja2 port
      - PyYAML
      - python-pip
      state: installed
    when: ansible_distribution == 'RedHat' and ansible_distribution_version.split(".")[0] == "7"

  - name: Ensure SCAP Security Guide Tests dependencies are installed (RHEL7)
    pip:
      name:
      - pytest
      - docker
    when: ansible_distribution == 'RedHat' and ansible_distribution_version.split(".")[0] == "7"

  - name: Ensure SCAP Security Guide dependencies are installed (RHEL8)
    package:
      name:
      - python3-jinja2
      - python3-pytest  # needed for unit tests + coverage
      - python3-PyYAML
      state: installed
    when: ansible_distribution == 'RedHat' and ansible_distribution_version.split(".")[0] == "8"

  - name: Ensure SCAP Security Guide Tests dependencies are installed (RHEL8)
    package:
      name:
      - podman
    when: ansible_distribution == 'RedHat' and ansible_distribution_version.split(".")[0] == "8"
